### PR TITLE
General: rename to xrootdpyfs

### PR DESCRIPTION
**Pull request by otron**
Addresses #65.

Updates the url in setup.py and package name as well, so this shouldn't be merged in until we've registered the new package name and renamed the repository.

### CODE REVIEW

**Comment by kiryx** [comment]
* Title underline should be two dashes longer: https://github.com/inveniosoftware/xrootdfs/pull/66/files#diff-dc8cf0cd192ecdec444dc298e9030bb3R105
* Some leftovers in non-code files when you run ``git grep xrootdfs`` from root dir of repo (e.g ``.coveragerc``, ``.travis.yml``, ``Dockerfile`` or ``README.rst`` etc.)

**Comment by kiryx** [comment]
The tests passed on Docker, except one error after the tests ran, where Sphinx's autodoc failed to find new name:
```
Warning, treated as error:
/home/xrootdfs/xrootdfs/docs/index.rst:6: WARNING: autodoc: failed to import module u'xrootdpyfs'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named xrootdpyfs
```

Could be that this goes away once the comments above are resolved.

**Comment by otron** [comment]
I've added more underlines and removed the remaining references to xrootdfs (`git grep -i xrootdfs` returns nothing).

I'm not getting the error you mention when running the tests in docker. Could you try running it again on the updated commit?

**Comment by kiryx** [comment]
I don't get an error anymore, but this was actually my fault. Looks good to me.

:shipit:

**Comment by kiryx** [comment]
I can also merge it if @lnielsen gives me push rights to this repository.

**Comment by lnielsen** [comment]
@kiryx Done. Remember to use ``git merge --ff-only`` (not the merge button). Also it's useful to fetch the pull requests from GitHub:

```console
$ git remote add upstream https://github.com/inveniosoftware/xrootdpyfs
$ cd xrootdpyfs
$ vim .git/config
```

and add the last line:

```
[remote "upstream"]
    url = git@github.com:inveniosoftware/xrootdpyfs.git
    fetch = +refs/heads/*:refs/remotes/upstream/*
    fetch = +refs/pull/*/head:refs/remotes/upstream/pr/*
```

Then you can merge:
```console
$ git fetch upstream
$ git merge --ff-only upstream/pr/<PR number>
```

**Pull request merged**
